# PostgreSQL
spring.datasource.url=jdbc:postgresql://pg:5432/studs?currentSchema=s408303
spring.datasource.username=s408303
spring.datasource.password=QSLc(0693

server.port=8081

spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.JBossAppServerJtaPlatform
spring.transaction.jta.enabled=true
spring.jpa.properties.jta.enabled=true

# JNDI DataSource
spring.datasource.jndi-name=java:/jdbc/gruzivezi
spring.datasource.type=org.springframework.jdbc.datasource.lookup.JndiDataSourceLookup