spring.cloud.compatibility-verifier.enabled=false
server.port=8081
google.sheets.spreadsheet.id=1H_OmmzfaLrZXHxMKLmlw0Vx_e7ZEbZgafEqARKvpnJ8
google.sheets.work.sheet.name=Sheet1
spring.application.name=billing-app


#spring.datasource.url=jdbc:postgresql://localhost:5432/gruzi_vezi
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true