spring.application.name=rzd-dispatcher
spring.cloud.compatibility-verifier.enabled=false


# PostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/gruzi_vezi
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false

# JTA - Narayana
spring.jta.enabled=true
spring.jta.narayana.transaction-manager-id=rzd-dispatcher
spring.jta.narayana.log-dir=./target/narayana-logs

# Eureka
eureka.client.serviceUrl.defaultZone=${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=${EUREKA_CLIENT_REGISTER_WITH_EUREKA:true}
eureka.client.fetch-registry=${EUREKA_CLIENT_FETCH_REGISTRY:true}
eureka.instance.prefer-ip-address=${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}

spring.jpa.properties.hibernate.current_session_context_class=jta
spring.data.redis.lazy-initialization=true
# Redis
spring.redis.host=${SPRING_REDIS_HOST:localhost}
spring.redis.port=${SPRING_REDIS_PORT:6379}
spring.quartz.startup-delay=15s
# Server
server.port=8080

# Logging
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql=ERROR
logging.level.com.arjuna=DEBUG
logging.level.org.jboss.narayana=DEBUG
logging.level.org.springframework.transaction=DEBUG

# JWT
jwt.expiration=86400000
jwt.refresh-expiration=604800000

#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/